name: CI main
on:
  push:
    branches: [ develop ]
jobs:
  main:
    name: Pruebas unitarias 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v4
    - name: Configuración de entorno de python
      uses: actions/setup-python@v4
      with:
          python-version: '3.8.0'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests -v