name: CI main
on:
  push:
    branches: [ develop ]
jobs:
  main:
    name: Pruebas 
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[run-release]')
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v5
    - name: Configuración de entorno de python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests -v