name: CI main
on:
  push:
    branches: [ develop ]
jobs:
  check-release:
    name: Verificar trigger de release 
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'run-release')
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
    - name: Extraer versión del commit
      id: extract-version
      run: |
        COMMIT_MSG="${{ github.event.head_commit.message }}"
        echo "Mensaje del commit: $COMMIT_MSG"
        
        # Buscar patrón [run-release:x.y.z] en el mensaje
        if [[ $COMMIT_MSG =~ \[run-release:([0-9]+\.[0-9]+\.[0-9]+)\] ]]; then
          VERSION="${BASH_REMATCH[1]}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Versión encontrada: $VERSION"
        else
          echo "No se encontró versión válida en el mensaje del commit"
          echo "Formato esperado: [run-release:1.2.0]"
          exit 1
        fi

  create-release:
    name: Crear rama release
    runs-on: ubuntu-latest
    needs: check-release-trigger
    if: needs.check-release.outputs.version != ''

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v5